### ISSUE TITLE
service_pull_request does not get set for travis-ci

### ISSUE THREAD

**Issue by cancan101** [coveralls-clients/coveralls-python#102]
https://github.com/coagulant/coveralls-python/blob/1a62ce2706ac73a521d231990e043886627bbf89/coveralls/api.py#L49-L52

Can use `TRAVIS_PULL_REQUEST`.

**Comment by nickmerwin** [comment]
Added PR here: https://github.com/coagulant/coveralls-python/pull/113

**Comment by TheKevJames** [comment]
PR is now merged, this will be a part of the next release.
