### ISSUE TITLE
Uploading doesn't work from local and travis

### ISSUE THREAD

**Issue by zloidemon** [coveralls-clients/coveralls-python#103]
I tried to send stats to coveralls.io: [error uploading](https://travis-ci.org/zloidemon/aiohttp_riak/jobs/106781068) i use same settings on [this](https://travis-ci.org/zloidemon/aiohttp_jrpc/jobs/87639028) but it works correctly.

**Comment by TheKevJames** [comment]
Looks like this was an [issue with coverage.py](https://bitbucket.org/ned/coveragepy/issues/434/indexerror-in-python-35) which was fixed in coverage.py v4.1.
