### ISSUE TITLE
.coveralls.yml has no effect

### ISSUE THREAD

**Issue by perrygeo** [coveralls-clients/coveralls-python#110]
I'm having troubles both locally and on travis-pro:

Locally, `coveralls` appears to ignore my `.coveralls.yml` file

```
$ coveralls
You have to provide either repo_token in .coveralls.yml, or launch via Travis or CircleCI
$ cat .coveralls.yml
repo_token: abcdefghijklmnop
```

and on travis-pro with `.coveralls.yml` set to 

```
service_name: travis-pro
repo_token: abcdefghijklmnop
```

the travis build logs tell me

```
$ coveralls
Submitting coverage to coveralls.io...
Coverage submitted!
Couldn't find a repository matching this job.
'url'
```

I've confirmed that the `repo_token` is equal to the token on the coveralls page. Am I missing a step? Options to debug this?

**Comment by johtso** [comment]
I'm having this same issue with a private repository in an organisation.

**Comment by coagulant** [comment]
https://github.com/coagulant/coveralls-python#troubleshooting

**Comment by johtso** [comment]
```
$ coveralls debug
Testing coveralls-python...
```

```json
{
    "config_file": ".coveragerc",
    "git": {
        "branch": "master",
        "head": {
            "author_email": "***",
            "author_name": "***",
            "committer_email": "noreply@github.com",
            "committer_name": "GitHub",
            "id": "52d164fd784a6deada45f4f463bba0a756d6978c",
            "message": "Merge f7859f1683447a66b96c8a72cb578d0cc4708335 into 13436d238574315b5485aadb49739b693eb98dff"
        },
        "remotes": [
            {
                "name": "origin",
                "url": "git@github.com:***/***.git"
            }
        ]
    },
    "service_job_id": "43213022",
    "service_name": "travis-ci",
    "source_files": [ ...
```

I have this in my `.travis.yml`:
```yml
env:
  - PYTHONPATH=. COVERALLS_SERVICE_NAME=travis-pro
```

and this is a `.coveralls.yml`:
```yml
service_name: travis-pro
```

**Comment by cancan101** [comment]
You need to install `pyyaml`.

**Comment by jcass77** [comment]
Adding ``pyyaml`` as a dependency worked for me both locally and using Travis - thanks!

**Comment by luiscoms** [comment]
I gess that this line [coveralls/api.py#L89](https://github.com/coagulant/coveralls-python/blob/master/coveralls/api.py#L89) would be logged on stdout to warn `pyyaml` dependency.

**Comment by codingjoe** [comment]
Same here. Please add a line of documentation, or better a warning.

**Comment by anjin** [comment]
@codingjoe Adding it now

**Comment by TheKevJames** [comment]
Looks like the log line was added after the most recent release. @goanpeca we should think about cutting our first release as soon as we can.

@goanpeca or @anjin or whoever wants to take care of this -- couple things we should do here:
- update the README to inform users to install `coveralls[yaml]` instead of `coveralls` when they want to use `.coveralls.yml`
- update [api.pi#L89](https://github.com/coveralls-clients/coveralls-python/blob/master/coveralls/api.py#L89) to inform users to change their dependency to `coveralls[yaml]`.

**Comment by TheKevJames** [comment]
We've cut release 1.2.0; this is now (finally) fixed!
