### ISSUE TITLE
Coverage info posted to ANOTHER repository

### ISSUE THREAD

**Issue by nazieb** [coveralls-clients/coveralls-python#114]
I was trying to use Coveralls.io in my company project. I followed the instructions in Coveralls dashboard to add a `.coveralls.yml` file, which looks like this:

``` yml
service_name: travis-pro
repo_token: somerandomstring
```

Then I decided to use this library to post the coverage, so I setup in my .travis.yml as instructed in this repository README. This what it looks like:

``` yml
language: python
python:
  - "3.5"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - nose2 --with-cover

after_success:
  coveralls
```

So I push the changes and take a look at the job executed in Travis dashboard. After the job is done, the coverage is also successfully posted to Coveralls.io. The log showed the job URL, something like this: https://coveralls.io/jobs/123445565. But when I check the Coveralls.io dashboard, it said that no build is posted yet to my repository.

So I decided to follow that link, and what I see is **my source code analysis posted to some random open source library repository in Coverals.io**. I don't know how that could happen, nor how to remove that analysis from that stranger repository.

Still in shock after revealing too much private information, I suspected that it had something to do with the Coveralls.io API, so I tried to regenerate the repo token key in Coveralls dashboard, and put it to the .coveralls.yml. But when I push the changes and the Travis job is done, this library said

```
Submitting coverage to coveralls.io...
Coverage submitted!
Couldn't find a repository matching this job.
'url'
```

Kind of clueless, I tried to use another [coveralls library](https://github.com/z4r/python-coveralls) with no further changes in the .coveralls.yml. And **it just worked**.

So I don't know what to report actually in this issue, perhaps the bug is on the Coveralls.io API, but after I found out that the other library works normally, I think that's not the full story.

Just trying to warn you before something like this happens again.

**Comment by TheKevJames** [comment]
Very much appreciate the report! I've pushed a few logging updates which should help capture this if it ever happens again, but I suspect this was likely a Coveralls.io error -- we're pretty much just blindly using their API.

Very sorry this happened to you!
