### ISSUE TITLE
504 gateway timeout

### ISSUE THREAD

**Issue by controversial** [coveralls-clients/coveralls-python#116]
Travis is saying `coveralls` succeeded, but there's no information on the website. If I look at the repo on Travis CI, and expand the log, I see HTML with really long raw bits of CSS and JavaScript. After scrolling through it for a while, I can see

``` html
<body id="errorPage">
    <div class="cf-error-details cf-error-504">
  <h1>Gateway time-out</h1>
  <p>The web server reported a gateway time-out error.</p>
  <ul class="cferror_details">
    <li>Ray ID: 2d25012b3279086e</li>
    <li>Your IP address: 52.22.60.255</li>
    <li>Error reference number: 504</li>
    <li>CloudFlare Location: Ashburn</li>
  </ul>
</div>
```

**Comment by TheKevJames** [comment]
Errors from the coveralls API should now actually generate an error case in `coveralls-python`. Thanks for the report!
