### ISSUE TITLE
Support: COVERALLS_SERVICE_NAME env var

### ISSUE THREAD

**Issue by kienpham2000** [coveralls-clients/coveralls-python#119]
I want to get rid of .coveralls.yml. It would be nice to have support reading this key:
COVERALLS_SERVICE_NAME

Use Case:
Private travis repo requires these 2 keys: COVERALLS_REPO_TOKEN and COVERALLS_SERVICE_NAME

**Comment by TheKevJames** [comment]
Great suggestion! This will be fixed in #167
