### ISSUE TITLE
Converting lcov

### ISSUE THREAD

**Issue by goanpeca** [coveralls-clients/coveralls-python#123]
We are working on a project with python and JS and the workflow for merging seems like a good idea except the workflow for transforming a lcov to a coveralls file seems unnecessarily convoluted.

I created in the meantime a python script that will take a lcov.info file and transform it into the appropriate format for merge usage.

I could make a PR so we could make this part of this package. @coagulant?

**Comment by coagulant** [comment]
Not sure, see #122

**Comment by goanpeca** [comment]
@TheKevJames what do you think of this one?

**Comment by TheKevJames** [comment]
I'm still trying to find the time to get a real handle of how this package works in the internals, I wouldn't mind a freeze for "big" features until then. That said, the idea of doing this seems like a good one to me.

**Comment by TheKevJames** [comment]
I finally had a chance to go through the documentation and [clean it all up](http://coveralls-python.readthedocs.io/en/latest/usage/multilang.html). As far as I understand, transforming the lcov.info into a coveralls-formatted JSON blob is as simple as

    coveralls-lcov -v -n coverage.info > coverage.json

Is that not the case?
