### ISSUE TITLE
source_files is empty

### ISSUE THREAD

**Issue by AndreasBackx** [coveralls-clients/coveralls-python#124]
I'm working on makinacorpus/django-safedelete#56 where I'm facing some troubles moving coveralls to tox. It doesn't report any files and when running `- coveralls debug` instead of `- coveralls` in tox, `source_files` is empty:

```json
{
    "config_file": ".coveragerc",
    "source_files": [],
    "service_name": "coveralls-python",
    "git": {
        "branch": "bug/can_hard_delete_fk",
        "remotes": [
            {
                "name": "origin",
                "url": "git@github.com:AndreasBackx/django-safedelete.git"
            },
            {
                "name": "upstream",
                "url": "git@github.com:makinacorpus/django-safedelete.git"
            }
        ],
        "head": {
            "author_name": "Andreas Backx",
            "id": "9861655e43d23c34a0bef6145ddf67ab2f9208f6",
            "author_email": "myemail",
            "committer_email": "myemail",
            "committer_name": "Andreas Backx",
            "message": "Moved coveralls to tox and ignore its exit code."
        }
    }
}
```

I can't see to figure out what is wrong and would appreciate it if you could point me in the right direction.

**Comment by TheKevJames** [comment]
Hey! Just wanted to leave a comment pointing out that you probably won't get a response on this until #122 is resolved.

**Comment by AndreasBackx** [comment]
@TheKevJames thanks for the reference. I'll keep an eye out.

**Comment by TheKevJames** [comment]
@AndreasBackx is this still an issue? If so: I've update `coveralls debug` to be a bit more usefully verbose. Could you re-run `coveralls debug` and paste the output?

**Comment by AndreasBackx** [comment]
We've held back on using tox with coveralls. @Gagaro might know more, I haven't done any work on it recently and I'm currently studying for exams.

**Comment by TheKevJames** [comment]
Ok -- I'm going to close this ticket, since I think this should be fixed by now, but if you @AndreasBackx or @Gagaro find it is not, feel free to re-open.
