### ISSUE TITLE
Add style checks for code

### ISSUE THREAD

**Issue by goanpeca** [coveralls-clients/coveralls-python#129]

**Comment by TheKevJames** [comment]
Let's combine this with automatic release generation. As a reference, I do this for a personal project here: https://github.com/TheKevJames/jarvis/blob/master/circle.yml#L47

**Comment by TheKevJames** [comment]
Agreed, let's use `pylint` or something like that. Quick glance of the codebase makes it look like very few style checks have been applied, let's make sure to do this carefully to avoid issues.

**Comment by goanpeca** [comment]
I will open a new issue for that.

What are your thoughts on pep8, isort, pycodestyle, pydocstyle, pylint, yapf.... I made this https://github.com/ContinuumIO/ciocheck to have all those check into one as part of the CI and if any test fails, the CI fails, so that we dont need to worry about style (lint warnings/erros) or format (yapf)

**Comment by TheKevJames** [comment]
Personally, I tend to use `pylint` and `pytest --pep8` -- happy to use any of the other checkers you mentioned. `ciocheck` looks pretty cool to me, though I'm not generally a fan of the auto-formatting part of those sorts of tools. The rest of that looks great to me, though!

**Comment by TheKevJames** [comment]
Fixed in #164
