### ISSUE TITLE
Add RELEASE.md file describing process

### ISSUE THREAD

**Issue by goanpeca** [coveralls-clients/coveralls-python#130]

**Comment by TheKevJames** [comment]
See my comment on https://github.com/coagulant/coveralls-python/issues/128 -- if we make the process as simple as that, this may be overkill.

**Comment by goanpeca** [comment]
Even if it is automatic, it is a good idea to have a description of what goes on to make all this.

**Comment by TheKevJames** [comment]
Good point, rather be as explicit as possible, anyway.
