### ISSUE TITLE
Join forces?

### ISSUE THREAD

**Issue by goanpeca** [coveralls-clients/coveralls-python#134]
@TheKevJames there is a package 

https://pypi.python.org/pypi/python-coveralls
https://github.com/z4r/python-coveralls

Should we contact and try to join forces?

We have more stars and forks...

**Comment by TheKevJames** [comment]
Seems reasonable, consolidation is good. I wonder if there's a reason there are two popular projects for this? Looks like they started around the same time and seem to do about the same time -- most likely the bulk of the functionality is duplicated between them.

**Comment by coagulant** [comment]
>I wonder if there's a reason there are two popular projects for this?

At the time of writing 3 years ago, python-coveralls was not opensourced yet, so I wrote my own.  
Having just one project is better for community, but merging is tedious, so I don't remember even asking Andrea about it.
