### ISSUE TITLE
Move repo to an organization

### ISSUE THREAD

**Issue by goanpeca** [coveralls-clients/coveralls-python#136]
For the sake of maintainability and also to enable easier control os CI services it would be much better to move this repo to a github organization

Thoughts @TheKevJames and @coagulant ?

I asked over https://github.com/lemurheavy/coveralls-public/issues/911

If the answer is not positive, I just created an organization called, [coveralls-clients](https://github.com/coveralls-clients)

If this does not already exists we could aggregate all other clients on this org.

**Comment by TheKevJames** [comment]
@coveralls-clients seems like a good idea. Less sure about moving to thcovvoeralls org itself -- that would probably be unlikely since it would look like official endorsement.

**Comment by goanpeca** [comment]
>Less sure about moving to thcovvoeralls org itself -- that would probably be unlikely since it would look like official endorsement.

Yep, my guess too, but it does not hurt to ask ;-)

**Comment by goanpeca** [comment]
@coagulant would you be ok with transferring this repo over to https://github.com/coveralls-clients ?

**Comment by coagulant** [comment]
@goanpeca I'm ok with that.

**Comment by TheKevJames** [comment]
Hey @coagulant, any progress on transferring this repo?

**Comment by coagulant** [comment]
@TheKevJames And it's done 🎉

**Comment by goanpeca** [comment]
Awesome thanks :-)

**Comment by TheKevJames** [comment]
Follow-up on this is to switch over things like TravisCI. I've requested access since I don't have owner permissions, but if you (@goanpeca) could mark me as an owner of @coveralls-clients, that'd be great.

**Comment by TheKevJames** [comment]
We'll also need to enable coveralls integration with this repo; I don't seem to be able to do that as a non-owner.

**Comment by goanpeca** [comment]
@TheKevJames I added you, could could you check if you have access now?

**Comment by TheKevJames** [comment]
Hmm doesn't seem to have worked. Looks like I'm still listed as a member, also.

![image](https://cloud.githubusercontent.com/assets/3341822/22941881/3f65df68-f2b5-11e6-9f8f-252ea8bec089.png)

**Comment by TheKevJames** [comment]
@goanpeca friendly reminder to look into these permissions

**Comment by goanpeca** [comment]
<img width="1268" alt="screen shot 2017-02-21 at 8 22 18 pm" src="https://cloud.githubusercontent.com/assets/3627835/23192819/809c0a20-f873-11e6-9e32-7a6acccc1a9e.png">
