### ISSUE TITLE
Add option to ignore abstract methods

### ISSUE THREAD

**Issue by nbro** [coveralls-clients/coveralls-python#137]
I don't know how this module is implemented, but it would be nice if we could specify to ignore abstract methods and the `@abstractmethod` annotation.

**Comment by TheKevJames** [comment]
Coverage reports are generated with [coverage.py](http://coverage.readthedocs.io/en/coverage-4.3.4/), this tool simply interprets the results and sends them along to coveralls.

As far as I know, coverage.py doesn't handle `@abstractmethod`s specially, but you may want to [configure coverage.py](http://coverage.readthedocs.io/en/latest/config.html) to handle this case. You can see more in the linked docs, but my best guess as to what you're looking for would be something like this (in a `.coveragerc` file in the root of your project):

```
[report]
exclude_lines =
    @abstractmethod
    raise NotImplementedError
```
