### ISSUE TITLE
Branch coverage

### ISSUE THREAD

**Issue by myint** [coveralls-clients/coveralls-python#143]
Apparently, Coveralls now supports branch coverage.

https://github.com/lemurheavy/coveralls-public/issues/31#issuecomment-284375195

I don't see the changes to the web API documented yet, but I do see that the Node client seems to support it via the `branches` key. `branches` is a sibling of `coverage` in the dictionary the client submits to Coveralls.

https://github.com/nickmerwin/node-coveralls/commit/15750503b69c3143b3020fa5d4fe4fc1d455356e
https://coveralls.io/github/nickmerwin/node-coveralls?branch=master

![screen shot 2017-03-06 at 07 58 43](https://cloud.githubusercontent.com/assets/1235108/23617741/ed18334e-0242-11e7-809c-5d91954e1670.png)

**Comment by nickmerwin** [comment]
@myint thanks for opening this -- you beat me to it!

We quietly released branch support over the weekend, and have been testing it with the node library.

I've updated the API reference here:
https://coveralls.zendesk.com/hc/en-us/articles/201350799

The new `branches` field is a compacted array of all branch data in the form:
```
[line-number, block-number, branch-number, hits, line-number-2, block-number-2, branch-number-2, hits-2,...]
```

Let me know how I can help get support for this landed for Python. Thanks!

**Comment by jvarho** [comment]
@nickmerwin What do block-number and branch-number mean? The data reported by coverage.py is arcs in the form (line_from, line_to). How would these correspond?

I implemented a hacky way to use branch coverage a while back when coveralls lacked actual support, so I could have a look at implementing this properly.

**Comment by nickmerwin** [comment]
Hi @jvarho here's the definition from lcov:
```
Branch coverage information is stored which one line per branch:

  BRDA:<line number>,<block number>,<branch number>,<taken>

Block number and branch number are gcc internal IDs for the branch. Taken is
either '-' if the basic block containing the branch was never executed or
a number indicating how often that branch was taken.
```
https://github.com/linux-test-project/lcov/blob/master/man/geninfo.1#L481

Could we map the coverage.py output to those? If not, I'd think we could default them to 0 and we'd achieve the same result re: detecting coverage increase/decrease.

**Comment by jvarho** [comment]
I tried my hand at this. I used what I called line_to above as the branch number to distinguish between the different branches from one line.

Very lightly tested, but does it seem to make sense?

**Comment by TheKevJames** [comment]
@myint thanks for the report! We really appreciate bringing this to our attention :)

@jvarho the PR looks great, thanks a bunch! I've added a couple comments, but it mostly looks good to me. 

@nickmerwin looks like @jvarho got it all figured out in #145, but if you'd like to weigh in, that'd be great. As far as I can tell, his PR does as you described, but it's always great to get another set of eyes.

This issue should be fixed with the associated PR and will land in the next release.

**Comment by nickmerwin** [comment]
@TheKevJames this looks great to me, has it been tested with a repo on Coveralls yet?

**Comment by TheKevJames** [comment]
@nickmerwin through our own CI, yes: https://coveralls.io/builds/10473882 . Looks like branch coverage there is "0 out of 0"... probably because we run `coverage.py` without `--branch`. I guess we should do that haha!

**Comment by nickmerwin** [comment]
@TheKevJames gotcha -- It may be worthwhile adding an check for `--branch` so as not to send along an empty `branches` parameter; the UI in Coveralls.io won't be crowded with 0/0 branch data that way.

**Comment by TheKevJames** [comment]
@nickmerwin Hmm... the current PR only tacks on the `branches` data if it could generate branch coverage (see: [the relevant line](https://github.com/coveralls-clients/coveralls-python/pull/145/files#diff-9ca443a68b05ef6494e6a8d2871058b3R117-118)), yet the "0/0" thing is still in the Coveralls.io UI.

In fact, even for Coveralls.io runs on other branches (ie. those that do not have the `branches` param), it still remarks that "0/0 branches" are covered (see: [coveralls run for different PR](https://coveralls.io/builds/10494598).

Am I missing something, or does Coveralls.io just always show that data now?

**Comment by nickmerwin** [comment]
@TheKevJames ah good call, that's fixed now -- branch coverage won't show for a build when total branches is zero, so no need for that extra check.

**Comment by jvarho** [comment]
@nickmerwin The branch statistics are not sent from the pull request branch. Can you explain the output on Coveralls side, though? If I look at e.g. this if in two runs:

https://coveralls.io/jobs/23666341/source_files/668170015#L184
https://coveralls.io/jobs/23666346/source_files/668170111#L184

Both runs take it one way and correctly report that the other one is missing. However, the aggregate stats claim the first one is missing (and twice?):

https://coveralls.io/builds/10504337/source?filename=coveralls%2Fapi.py#L184

**Comment by nickmerwin** [comment]
@jvarho great catch, ok that's fixed now:

https://coveralls.io/builds/10504337/source?filename=coveralls%2Fapi.py#L184
