### ISSUE TITLE
How to restrict pytest to specific folder for testing

### ISSUE THREAD

**Issue by michaelaye** [coveralls-clients/coveralls-python#144]
Hello!
I'm using the given cmd from your README successfully in my travis setup:

```yml
script:
 - coverage run --source=pyciss setup.py test
```

How do I have to adapt this to let `pytest` know to only test in one specific folder?
And would the coverage still be correctly calculated in that case?

Thanks for your package!

**Comment by goanpeca** [comment]
Hi @michaelaye you need to create a conifguration file for pytest 

```
# first look for pytest.ini files
path/pytest.ini
path/setup.cfg  # must also contain [tool:pytest] section to match
path/tox.ini    # must also contain [pytest] section to match
pytest.ini
... # all the way down to the root

# now look for setup.py
path/setup.py
setup.py
... # all the way down to the root
```

And you can setup which paths to use http://doc.pytest.org/en/latest/customize.html#confval-testpaths

**Comment by michaelaye** [comment]
I see, thanks. Was kinda hoping I can avoid yet another confit file in my package but so be it. ;)
