### ISSUE TITLE
Travis build failing due to coveralls 

### ISSUE THREAD

**Issue by tusharmakkar08** [coveralls-clients/coveralls-python#154]
Hey 

I am a contributor to [Voluptuous](https://github.com/alecthomas/voluptuous). We use coveralls for coverage related stats. 
However, our [latest build](https://travis-ci.org/alecthomas/voluptuous/jobs/231428779) was errored out due to coveralls (Looks like docopt only supports python version >= 3.3, however we support Python 3.2 as well). How to get it fixed?

Thanks.

**Comment by TheKevJames** [comment]
Hi there!

Unfortunately, `coveralls-python` _also_ only officially supports Python versions >= 3.3. Python 3.2 was end-of-life'd [over a year ago](https://www.python.org/dev/peps/pep-0392/#lifespan) and I would recommend migrating away from it; indeed, even version 3.3 will be end-of-life'd by [the end of the year](https://www.python.org/dev/peps/pep-0398/#lifespan).

That said, I understand there is sometimes the need to continue using outdated software. You might consider pinning `coveralls-python` and any dependencies such as `docopt` to versions which support older python installations -- be warned that you may be missing bugfixes and security fixes in that case.
