### ISSUE TITLE
coveralls installation issue?

### ISSUE THREAD

**Issue by ramsinghdayal** [coveralls-clients/coveralls-python#157]
#coveralls-1.1 (https://pypi.python.org/pypi/coveralls)
C:\Users\RD\Anaconda3\pkgs_rd\coveralls-1.1>pip install setup.py
Error: could not find the version that satisfies the requirement setup.py
Version: Python 3.6.1 !Anaconda 4.4.0 (32-bit) ! (default, date, time) [MSC v.1 900 32 bit (intel)] on win32

**Comment by TheKevJames** [comment]
To install `coveralls-python` please either use

    pip install coveralls

to install the most recent release, or

   python setup.py install

in your cloned repository to install from source. `pip install setup.py` would be searching the Python package repository for a package named `setup.py`.
