### ISSUE TITLE
Normalize file paths between POSIX and Windows

### ISSUE THREAD

**Issue by koterpillar** [coveralls-clients/coveralls-python#159]
I am running builds for https://github.com/aloetesting/aloe on Travis CI and AppVeyor (for Windows). On Windows, directory and file names are separated by a backslash (\), everywhere else it is a forward slash (/).

Coveralls should normalize the paths coming from different build systems to properly merge the files coverage.

**Comment by TheKevJames** [comment]
Thanks for the report! I'll put this on my backlog. PRs are always welcome, as well :)

Sort-of a duplicate of #118.

**Comment by TheKevJames** [comment]
@koterpillar this issue should now be resolved as of [release 1.5.0](https://github.com/coveralls-clients/coveralls-python/releases/tag/1.5.0).
