### ISSUE TITLE
Make package executable

### ISSUE THREAD

**Issue by Kentzo** [coveralls-clients/coveralls-python#183]
Adding the `__main__.py` file to the package will make possible executing via `python -m coveralls`.

It helps to run right version of coveralls instead of relying on the `PATH` configuration.

**Comment by TheKevJames** [comment]
@Kentzo good call -- I've opened a PR to fix this and will make sure its a part of the next release.

**Comment by TheKevJames** [comment]
@Kentzo released as of [version 1.5.0](https://github.com/coveralls-clients/coveralls-python/releases/tag/1.5.0).
