### ISSUE TITLE
Coveralls client only exposes `coveralls` command entry point

### ISSUE THREAD

**Issue by ryan-summers** [coveralls-clients/coveralls-python#194]
When performing a pip install of `coveralls`, a command-line entry point is made for `coveralls`. This conflicts with other coveralls clients (such as `cpp-coveralls`) that also create a command-line entry point named `coveralls`. It would make sense to expose an additional, unique command-line entry point `coveralls-python` that can be used exclusively for referring to this package.

**Comment by TheKevJames** [comment]
That seems reasonable to me -- I'd be happy to accept a PR which adds the secondary command line entry beside the first.

**Comment by Julian** [comment]
`python -m coveralls` already seems to exist and work, so to me this may not be necessary given you can just use that if the binary name is used by some other thing.

**Comment by ryan-summers** [comment]
@Julian That seems like a good approach to me as well, thanks for pointing that out.

I'm going to close this since that's an appropriate work-around.
