### ISSUE TITLE
KeyError: 'url' and no result on coveralls.io

### ISSUE THREAD

**Issue by white-gecko** [coveralls-clients/coveralls-python#195]
`coveralls` executes with the following output and now coverage report is pushed to coveralls.

```
Submitting coverage to coveralls.io...
Coverage submitted!
Couldn't find a repository matching this job.
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/bin/coveralls", line 11, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coveralls/cli.py", line 80, in main
    log.info(result['url'])
KeyError: 'url'
```

The problem is occurring on this pull request:
https://github.com/AKSW/QuitStore/pull/221

The output can be seen here:
https://travis-ci.org/AKSW/QuitStore/jobs/495597359

And I've also enabled `coveralls debug` in the next commit:
https://travis-ci.org/AKSW/QuitStore/jobs/495675977

**Comment by white-gecko** [comment]
On a later pull request everything is fine again: https://github.com/AKSW/QuitStore/pull/222

**Comment by TheKevJames** [comment]
Yeah, we're starting to get more and more reports of the coveralls API behaving oddly like this and returning varying results. For now the workaround is to simply retry; looks like their API is working nine times out of ten.

That said, we should update our code to avoid throwing an error here on missing keys -- its important that the job fails, but we should make sure our logging captures the real error. We might even be able to / want to automatically retry in this case.

**Comment by TheKevJames** [comment]
I've cut a new release ([1.7.0](https://github.com/coveralls-clients/coveralls-python/releases/tag/1.7.0)) which should include better debugging for issues like this. Let us know if you see this problem again!
