### ISSUE TITLE
Usage in azure-pipelines

### ISSUE THREAD

**Issue by asottile** [coveralls-clients/coveralls-python#196]
Hi!

I'm wondering what is needed / how I could help to get coveralls to work with azure-pipelines in a similar mode as travis-ci / circle-ci where a token isn't necessary:

```
[command]/bin/bash --noprofile --norc /home/vsts/work/_temp/ba7f4711-0da1-4224-82a8-4ef365d4087f.sh
Not on Travis or CircleCI. You have to provide either repo_token in .coveralls.yml or set the COVERALLS_REPO_TOKEN env var.
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/2.7.15/x64/lib/python2.7/site-packages/coveralls/cli.py", line 60, in main
    service_name=options['--service'])
  File "/opt/hostedtoolcache/Python/2.7.15/x64/lib/python2.7/site-packages/coveralls/api.py", line 59, in __init__
    self.ensure_token()
  File "/opt/hostedtoolcache/Python/2.7.15/x64/lib/python2.7/site-packages/coveralls/api.py", line 68, in ensure_token
    self.config_filename))
CoverallsException: Not on Travis or CircleCI. You have to provide either repo_token in .coveralls.yml or set the COVERALLS_REPO_TOKEN env var.
##[error]Bash exited with code '1'.
```

I'm happy to help implement this if I'm given some direction -- thanks in advance!

**Comment by asottile** [comment]
oh, I realize this is the wrong place to ask -- I'll ask in the official repo

**Comment by TheKevJames** [comment]
@asottile no worries about opening it here -- if there's anything `coveralls-python` would need to do to support Azure Pipelines, it'd be great to hear about it. In the meantime, though, it looks like the [official Coveralls documentation does not list Azure Pipelines as supported](https://docs.coveralls.io/supported-ci-services), so my guess would be that you need to use a token.
