### ISSUE TITLE
FileNotFoundError exception when `git` is not installed

### ISSUE THREAD

**Issue by colecrtr** [coveralls-clients/coveralls-python#198]
Command:
```
docker-compose exec -T \
  -e GIT_BRANCH=$BITBUCKET_BRANCH \
  -e GIT_ID=$BITBUCKET_COMMIT \
  -e GIT_AUTHOR_NAME="$(gitlog %aN)" \
  -e GIT_AUTHOR_EMAIL="$(gitlog %ae)" \
  -e GIT_COMITTER_NAME="$(gitlog %cN)" \
  -e GIT_COMITTER_EMAIL="$(gitlog %ce)" \
  -e GIT_MESSAGE="$(gitlog %s)" \
  django coveralls debug
```

Output:
```
Missing .coveralls.yml file. Using only env variables.
Testing coveralls-python...
Failed collecting git data. Are you running coveralls inside a git repository? Is git installed?
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/coveralls/git.py", line 68, in git_info
    'id': gitlog('%H'),
  File "/usr/local/lib/python3.6/site-packages/coveralls/git.py", line 29, in gitlog
    '--pretty=format:{}'.format(fmt))
  File "/usr/local/lib/python3.6/site-packages/coveralls/git.py", line 13, in run_command
    stderr=subprocess.PIPE)
  File "/usr/local/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git': 'git'
```

I'm running `coveralls` within the docker-compose `django` service I've defined, passing in the necessary `GIT_*` environment variables used in this `except` section: https://github.com/coveralls-clients/coveralls-python/blob/master/coveralls/git.py#L78

The  `git --no-pager log -1 --pretty=format:%H` command fails and subprocess raises a `FileNotFoundError` exception which is not a listed exception in the `except` statement linked above. I believe it should be since the whole point of it is to `except` the case where `git` is not being used.

**Comment by colecrtr** [comment]
I'd be happy to branch & PR the necessary change, I only need the GitHub permissions to do so.

**Comment by TheKevJames** [comment]
@colecrtr thanks for the bug report -- I've fixed this issue and will release a new version of `coveralls` including that patch shortly!

For the future: you should be able to fork this repo and make changes there; GitHub's flow for making PRs between repos is pretty slick.
