### ISSUE TITLE
What does the output code 29724 mean?

### ISSUE THREAD

**Issue by davidwagner** [coveralls-clients/coveralls-python#202]
When I try to run `coveralls` to upload a coverage report, nothing gets uploaded and the only output I get is `29724`.  I don't know what that means.  Is that an error code?  How do I troubleshoot this further?  Any advice on what to check next?

```
$ coveralls --verbose       
Submitting coverage to coveralls.io...
29724
$ coveralls debug
Testing coveralls-python...
29724
$ coveralls --output=coveralls.out 
Write coverage report to file...
29724
$ cat coveralls.out 
$ pip list | egrep -i 'pytest|coverage|coveralls'
coverage                      3.7.1    
coveralls                     0.5      
pytest                        4.6.2  
$ python --version
Python 3.7.3
```

Coveralls used to work from within Travis (e.g., https://travis-ci.org/data-8/datascience/builds/402003674#L2137-L2141); it stopped working at some point in the last 11 months, and I'm not sure why (e.g., https://travis-ci.org/data-8/datascience/builds/543977273#L2401-L2403).  The only thing I can see that is changed is switching from Python 3.4 to Python 3.6 on Travis; none of the other coveralls or Travis configuration files have changed.

**Comment by TheKevJames** [comment]
Well that's terrible output! I can't say I've ever seen that before -- looks like our exception handler is doing something really weird here. Looks like `coveralls.api.Coveralls.wear()` is raising an unhandled exception with a useless error message, or the error message isn't getting passed through correctly.

Could you try removing [this exception handler](https://github.com/coveralls-clients/coveralls-python/blob/master/coveralls/cli.py#L85) so we can see what the stack trace here is? My current best guess is that this might be [this KeyError getting re-raised](https://github.com/coveralls-clients/coveralls-python/blob/master/coveralls/reporter.py#L66).

**Comment by davidwagner** [comment]
Oops!  This was my fault.  For some reason I was picking up very old versions of coverage and coveralls.  When I wiped my install of all old versions of those dependencies and reinstalled fresh versions, now everything works right.  PEBKAC.  I apologize for wasting your time with this.

**Comment by TheKevJames** [comment]
No problem, thanks for letting me know!
