### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte

### ISSUE THREAD

**Issue by evandrocoan** [coveralls-clients/coveralls-python#205]
All my buildings are working/passing, except the one which runs coveralls: 

1. https://ci.appveyor.com/project/evandrocoan/pythondebugtools/builds/26452374
    ![image](https://user-images.githubusercontent.com/5332158/62418077-067fb500-b637-11e9-96dd-9be6a6d4e453.png)

1. https://ci.appveyor.com/project/evandrocoan/pythondebugtools/builds/26452411
    ```
    IF "%COVERAGE%"=="py36" (coveralls debug)
    usage: coveralls [-h] [--coveralls_url COVERALLS_URL] [--base_dir BASE_DIR]
                     [--data_file DATA_FILE] [--config_file CONFIG_FILE]
                     [--coveralls_yaml COVERALLS_YAML] [--ignore-errors]
                     [--merge_file MERGE_FILE] [--nogit] [--skip_ssl_verify]
    coveralls: error: unrecognized arguments: debug
    Command exited with code 2
    ```
1. https://ci.appveyor.com/project/evandrocoan/PythonDebugTools/build/job/cctj5ifpx21hsp84
    ```
    IF "%COVERAGE%"=="py36" (coveralls)
    Traceback (most recent call last):
      File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "c:\python36\lib\runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "C:\Python36\Scripts\coveralls.exe\__main__.py", line 9, in <module>
      File "c:\python36\lib\site-packages\coveralls\__init__.py", line 93, in wear
        source_files=coverage.coveralls(args.base_dir, ignore_errors=args.ignore_errors, merge_file=args.merge_file),
      File "c:\python36\lib\site-packages\coveralls\control.py", line 9, in coveralls
        return reporter.report(base_dir, ignore_errors=ignore_errors, merge_file=merge_file)
      File "c:\python36\lib\site-packages\coveralls\report.py", line 16, in report
        source = fp.readlines()
      File "c:\python36\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 3241: character maps to <undefined>
    Command exited with code 1
    ```

**Comment by evandrocoan** [comment]
My files encoding is not `cp1252.py` but UTF-8 as declared on the start of each python file on my project:
```
#! /usr/bin/env python
# -*- coding: utf-8 -*-
...
```

**Comment by evandrocoan** [comment]
My Python python-coveralls version is 2.9.3

**Comment by evandrocoan** [comment]
I install it with `pip install --disable-pip-version-check python-coveralls` and my pip version is:
```` 
pip 18.1 from c:\python36\lib\site-packages\pip (python 3.6)
````

**Comment by TheKevJames** [comment]
@evandrocoan looks like there's a bit of a naming collision going on here: this project is the `coveralls` package on PyPI. The `python-coveralls` package would be [this repo](https://github.com/z4r/python-coveralls). You'll need to seek help with them.

Sorry for the confusion! If you `pip install coveralls` instead, we'd be happy to help :P

**Comment by evandrocoan** [comment]
I see, I will do not what all these names mean, but I created a new matrix rule just to run this coveralls, while I kept the other coverage tools running on the old rule: https://github.com/evandrocoan/debugtools/commit/03b6eeaf1c7a8269aa2494e12cdb3b6dcd6dce11

**Comment by TheKevJames** [comment]
What I mean to say is that you are not using the `coveralls` from this repo. You're using [this other package](https://github.com/z4r/python-coveralls) from a different repo entirely -- unfortunately, it looks like both of these packages were created around the same time: we registered the `coveralls` name on PyPI (eg. `pip install coveralls` installs from this repo). That other project registered `python-coveralls` (eg. `pip install python-coveralls`) sometime afterwards; you need to be looking at their repo (https://github.com/z4r/python-coveralls) for any debugging help.

**Comment by evandrocoan** [comment]
@TheKevJames, what I also meant with my last message is that I stopped using their coveralls and now I am using this coveralls and it is working 100%.

**Comment by TheKevJames** [comment]
Oh, gotcha! Sorry, completely misunderstood.

Well, great to hear! Feel free to let me know if you have any future issues. :)
