### ISSUE TITLE
coveralls 1.10.0 does not work with coverage 5.0.2

### ISSUE THREAD

**Issue by bcl** [coveralls-clients/coveralls-python#217]
Travis test run from pykickstart project:

https://travis-ci.org/pykickstart/pykickstart/jobs/633359771

It works fine if I limit coveralls to < 1.10.0 in our requirements.txt, with that it installs:

   coverage-4.5.4 coveralls-1.9.2

**Comment by agronholm** [comment]
I don't see what this problem has to do with coveralls itself.

**Comment by bcl** [comment]
```
Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/coverage/sqldata.py", line 1033, in execute

    return self.con.execute(sql, parameters)

sqlite3.OperationalError: no such table: meta
```

Doesn't happen with 4.5.4, I don't know anything about the internals of coveralls or coverage but it looks like something changed in the 5.x series that coveralls doesn't setup correctly. Or maybe this is a coverage problem?

**Comment by agronholm** [comment]
At that point your test suit is not even touching coveralls. Thus, not a coveralls problem. Should be easy to test locally against different version of coverage, yes?

**Comment by bcl** [comment]
Thanks, I can reproduce it without coveralls installed at all so it appears to be a coverage issue.
