### ISSUE TITLE
Add support for Coverage version 5

### ISSUE THREAD

**Issue by rubickcz** [coveralls-clients/coveralls-python#221]
Hello,

since `coverage` version 5.0, `coveralls` fails to run:

```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/bin/coveralls", line 10, in <module>
    sys.exit(wear())
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/coveralls/__init__.py", line 78, in wear
    from coveralls.control import coveralls
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/coveralls/control.py", line 2, in <module>
    from coveralls.report import CoverallsReporter
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/coveralls/report.py", line 6, in <module>
    from coverage.report import Reporter
ImportError: cannot import name 'Reporter'
```

Do you plan to add support for `coverage` 5.0 and above?

**Comment by TheKevJames** [comment]
We introduced coverage v5 support in coveralls v1.10 -- see the [release notes](https://github.com/coveralls-clients/coveralls-python/releases/tag/1.10.0). You can see [this test run](https://github.com/coveralls-clients/coveralls-python/runs/462653516) on the latest commit to master which passes tests under Py3.6.7 with coverage5. Could you please paste the output of `pip freeze` to help debug what's going wrong here?

**Comment by rubickcz** [comment]
Oh, I realized that the problem is with a different package, which is similary named: https://github.com/z4r/python-coveralls

My fault, I'm sorry. This issue is not relevant here, I'm closing it.

**Comment by TheKevJames** [comment]
No problem -- our libraries get confused a lot! Looks like that one doesn't support cov5 at all (see [issue](https://github.com/z4r/python-coveralls/issues/73)), unfortunately.
