### ISSUE TITLE
confusion with "COVERALLS_PARALLEL" and running on two CI services

### ISSUE THREAD

**Issue by AndrewAnnex** [coveralls-clients/coveralls-python#226]
For my project, I currently run tests on travis CI for linux and macos and appveyor for windows. Currently I have only reported coverage results to coveralls with travis CI, but with two CI services I am seeing confusing issues. 1. Builds from both CI services have different build numbers, 2 the appveyor builds are not reporting coverage for different jobs (I run tests on Python 3.6, 3.7, 3.8) like they do for travis builds. 

Ideally, I would have a single build in coveralls with all of the different build jobs from travis and appveyor aggregated, if not I would at least like to see each job reported for appveyor.

Do I need to change the coveralls_parallel variable in some way?

PR (https://github.com/AndrewAnnex/SpiceyPy/pull/368) to follow progress and changes

**Comment by TheKevJames** [comment]
Yes indeed; when you want multiple CI runs to get aggregated together you [need to set `COVERALLS_PARALLEL=true` in your environment](https://coveralls-python.readthedocs.io/en/latest/usage/configuration.html).

Unfortunately, I think the above will only work for a single CI service: it looks like [coveralls still does not support aggregating across CI services](https://github.com/lemurheavy/coveralls-public/issues/613). Unfortunately, we can't support this until they offer that feature in their API, sorry :(
