### ISSUE TITLE
Unable to submit coverage during re-run travis jobs

### ISSUE THREAD

**Issue by r0ps3c** [coveralls-clients/coveralls-python#238]
Whenever trying to re-run a travis ci job, submitting to coveralls.io fails with:

```422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs```

Additional debugging indicates this is due to the job id not being unique, as the submit/post returns an error of the form:

```service_job_id (XXXXXXX) must be unique for Travis Jobs not supplying a Coveralls Repo Token```

**Comment by TheKevJames** [comment]
Forgot to close this one -- thanks again for the PR!
