### ISSUE TITLE
Recipe for using coveralls with Azure Pipelines

### ISSUE THREAD

**Issue by wumpus** [coveralls-clients/coveralls-python#245]
Coveralls doesn't support Azure Pipelines, but here's how to use coveralls to submit to coveralls.io by pretending to be Circle CI.

1) Add this script to the end of your pipeline
```
    - script: |
        pip install coveralls
        export CIRCLE_BRANCH=$BUILD_SOURCEBRANCH
        coveralls
      displayName: 'coveralls'
      env:
        CIRCLECI: 1
        CIRCLE_BUILD_NUM: $(Build.BuildNumber)
        COVERALLS_REPO_TOKEN: $(coveralls_repo_token)
```

2) use the Azure Pipelines web UI to add a variable to this pipeline named `coveralls_repo_token` with the `token` from the coveralls.io website. Do not check the "keep this value secret" box. This is secure enough, in that a user making a Pull Req cannot access this variable.

**Comment by TheKevJames** [comment]
Thanks @wumpus! I've added the above to our documentation.
