### ISSUE TITLE
On GitHub Actions, finish fails with `coveralls.exception.CoverallsException: Parallel finish failed: Invalid github token`

### ISSUE THREAD

**Issue by exarkun** [coveralls-clients/coveralls-python#248]
I'm trying to start using coveralls on a project.  I have parallel builds on GitHub Actions so I am using the parallel feature.

The finish job fails though:

The GitHub Actions configuration is:

```
  # Tell Coveralls that we're done reporting coverage data.  Since we're using
  # the "parallel" mode where more than one coverage data file is merged into
  # a single report, we have to tell Coveralls when we've uploaded all of the
  # data files.  This does it.  We make sure it runs last by making it depend
  # on *all* of the coverage-collecting jobs.
  finish-coverage-report:
    # There happens to just be one coverage-collecting job at the moment.  If
    # the coverage reports are broken and someone added more
    # coverage-collecting jobs to this workflow but didn't update this, that's
    # why.
    needs:
      - "coverage"
    runs-on: "ubuntu-latest"
    # Get a Python 3 environment because only the Python 3 release of
    # coveralls-python has the `--finish` flag...
    container: "python:3-slim"
    steps:
      - name: "Finish Coveralls Reporting"
        run: |
          # Also install wheel otherwise `docopt` may fail to build
          pip install wheel coveralls
          python -m coveralls --finish
        env:
          # Some magic value required for some magic reason.
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          # Help coveralls identify our project.
          COVERALLS_REPO_TOKEN: "..."
```

also visible at
https://github.com/tahoe-lafs/tahoe-lafs/blob/9a8a61b74042a8870e83e4700a177627e02a528a/.github/workflows/ci.yml#L82-L108

The failure looks like this:

```
Finishing parallel jobs...
Parallel finish failed: Invalid github token
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/coveralls/cli.py", line 80, in main
    coverallz.parallel_finish()
  File "/usr/local/lib/python3.9/site-packages/coveralls/api.py", line 268, in parallel_finish
    raise CoverallsException('Parallel finish failed: {}'.format(e))
coveralls.exception.CoverallsException: Parallel finish failed: Invalid github token
Error: Process completed with exit code 1.
```

and is also (presently) visible at https://github.com/tahoe-lafs/tahoe-lafs/runs/1653828599?check_suite_focus=true

I tried to collect output from `coverage debug --finish` but it looks like it's evidence of some unrelated problem:

```
Missing .coveralls.yml file. Using only env variables.
Testing coveralls-python...
Failed collecting git data. Are you running coveralls inside a git repository? Is git installed?
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/coveralls/git.py", line 79, in git_info
    'id': gitlog('%H'),
  File "/usr/local/lib/python3.9/site-packages/coveralls/git.py", line 25, in gitlog
    glog = run_command('git', '--no-pager', 'log', '-1',
  File "/usr/local/lib/python3.9/site-packages/coveralls/git.py", line 12, in run_command
    cmd = subprocess.Popen(list(args), stdout=subprocess.PIPE,
  File "/usr/local/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git'
{"source_files": [], "config_file": ".coveragerc", "repo_token": "[secure]", "service_name": "github-actions", "service_number": "464933209", "service_pull_request": "956"}
```

this is also (presently) visible at https://github.com/tahoe-lafs/tahoe-lafs/runs/1653903051?check_suite_focus=true

**Comment by TheKevJames** [comment]
@exarkun the first issue you've listed there seems to be related to some Github Actions issues I've just fixed -- see #240 and #247 for more info. Updating to version 3.0.0 should do the trick!

You can also remove the `COVERALLS_REPO_TOKEN` value in your config (the `GITHUB_TOKEN` is enough). It should be ignored since you've set the `GITHUB_TOKEN`, but removing it would help make sure.

Your second issue is more straightforward -- it looks like you're running commands in an environment which does not have `git` installed? We require the ability to run `git log` commands against your code in order for coveralls to know how to match coverage reports to your repo. Ensuring you usage a base image with git and have access to your code from the GH Actions job should do the trick!

**Comment by exarkun** [comment]
Hi @TheKevJames thanks for your response.

Regarding `git` being missing, I modeled my configuration on https://coveralls-python.readthedocs.io/en/latest/usage/configuration.html#github-actions-support which also uses the `python:3-slim` Docker image.  So if that image is unsuitable, it would probably be helpful to have that documentation updated to suggest a different image.

Also, if git is missing, maybe `coveralls-python` could fail by saying Git is missing instead of failing by saying "Invalid github token".  This might help more people diagnose the problem on their own.

**Comment by TheKevJames** [comment]
@exarkun yes, sorry about that, I was indeed referring to the second error, eg. the one which outputs `Failed collecting git data. Are you running coveralls inside a git repository? Is git installed?`.

Hopefully, v3.0.0 has solved your normal usage (rather than `debug` mode) issue?

**Comment by AngellusMortis** [comment]
This issue happens on a self-hosted/Enterprise instance of Coveralls as well. It seems like for the Parallel Finish step it is expecting the `COVERALLS_REPO_TOKEN`. In general, it looks like everything "works" (having an issue with coverage being reported, but everything succeeds) with the `COVERALLS_REPO_TOKEN`.
