### ISSUE TITLE
Update 3.0.0 Release Notes

### ISSUE THREAD

**Issue by davidmezzetti** [coveralls-clients/coveralls-python#251]
Thank you for the great work on this package.

Upon running a build today on GitHub actions, coveralls.io submission failed with a `422 Client Error: Unprocessable Entity` error when submitting to coveralls.io. 

The release notes look to have a typo (it says to set `service-name` vs `service`) on the command to override the service name. 

With my GitHub actions build I had to run:

```
coveralls --service=github
```

When setting this option, the submission to coveralls started working again.

**Comment by TheKevJames** [comment]
Thanks for the bug report! And special thanks to @icemac for fixing this in #250. Both the release notes and the docs have now been updated. Sorry for any inconvenience!

**Comment by TimoRoth** [comment]
Isn't the actual issue here that running in Github Actions is no longer properly auto-detected, and not the documentation about the service name being wrong?

**Comment by davidmezzetti** [comment]
There is a pinned issue here - https://github.com/TheKevJames/coveralls-python/issues/252

Sounds like there is no known solution for auto detection at this time.

**Comment by TheKevJames** [comment]
Yeah, the big issue is that we _can_ autodetect Github Actions, but we _can't_ autodetect which service name Github Actions needs for this specific run. As far as we can tell at this point, the only option is for users to set the explicit name if their usecase requires a non-default service name.
