### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by sankarravi** [coveralls-clients/coveralls-python#64]
We're running coveralls via CircleCI. On one of our branches today, we're seeing this error:

```
Testing coveralls-python...
ERROR: While preparing JSON received exception: 'ascii' codec can't decode byte 0xe2 in position 240: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/ubuntu/virtualenvs/venv-2.7.8/bin/coveralls", line 9, in <module>
    load_entry_point('coveralls==0.5', 'console_scripts', 'coveralls')()
  File "/home/ubuntu/virtualenvs/venv-2.7.8/lib/python2.7/site-packages/coveralls/cli.py", line 54, in main
    coverallz.wear(dry_run=True)
  File "/home/ubuntu/virtualenvs/venv-2.7.8/lib/python2.7/site-packages/coveralls/api.py", line 78, in wear
    json_string = self.create_report()
  File "/home/ubuntu/virtualenvs/venv-2.7.8/lib/python2.7/site-packages/coveralls/api.py", line 101, in create_report
    self.debug_bad_encoding(data)
UnboundLocalError: local variable 'data' referenced before assignment
```

That's the output of `coverall debug` but we get the same error when running the regular `coveralls` command.

The CircleCI container is running Python 2.7.8 in a virtualenv on Ubuntu. It's running `pip install coveralls`, which looks like it's installing coveralls-0.5.

Presumably there are at least two bugs here:
1. Some kind of encoding / UTF-8 issue in the data on this branch
2. The UnboundLocalError preventing useful debugging info from being printed about number 1.

Hopefully at least that second one is a straightforward bug.

**Comment by coagulant** [comment]
Hi. I've fixed `UnboundLocalError` in latest commit, thnx.
Unfortunately, this won't be very helpful to debug first bug.

My guess, it's git command output causing problem.
Could you please run coveralls debug again using latest github version of coveralls?

**Comment by sankarravi** [comment]
Now I see:
```
Testing coveralls-python...
Source file hedto_rtf_runner.py can not be properly decoded, skipping. Please check if encoding declaration is ok
Source file is not python formulary/lookup
{"repo_token": "[secure]", "service_name": "coveralls-python", "git":...
```
The rest of the command contains lots of source, so I can't really upload that here, but I can upload hedto_rtf_runner.py if you think whatever is unique about its encoding is likely to survive the process of me editing it a bit and uploading it here. SublimeText reports that it's just UTF-8 encoded.

Worth noting that when I just run `coveralls` with this version, the job will eventually successfully submit (just with that message about hedto_rtf_runner)

**Comment by coagulant** [comment]
In coveralls `hedto_rtf_runner.py` encoding (as any other python-file) is determined by encoding declaration on top of file (algo is borrowed from coverage.py).

If coveralls debug works ok now, it means that maybe a very specific commit was causing `UnicodeDecodeError`. Was there something odd about it's original commit message/branch/commiter name, etc?
Here is the code that might cause problems:
https://github.com/coagulant/coveralls-python/blob/master/coveralls/api.py#L166-202

**Comment by sankarravi** [comment]
>If coveralls debug works ok now, it means that maybe a very specific commit was causing UnicodeDecodeError
I think that what was happening was that the single encoding issue caused the whole `coveralls` command to fail, because the `UnboundLocalError` halted program execution. So after fixing that, the submission continued to run... just with one file left out.

We did find that `hedto_rtf_runner.py` had some kind of Unicode line separator accidentally inserted in the top of the file. So that seems to address the first issue.

If you want to make coveralls more resilient to getting input like that, we can keep the ticket open and I can get you a copy of the file. If not, just the fix you've already made is sufficient to prevent coveralls from crashing when it runs into invalid characters, and you can close the ticket. It would be nice to ship a new release to pypi so that bug fix gets picked up, though. Thanks!

**Comment by coagulant** [comment]
I'm not sure why `debug_bad_encoding` didn't run in the first place, as it's specifically there to catch files with bad encodings while generating json data (#15). Moving `create_data` out of try-except block is not fixing the cause of why `UnboundLocalError` happened (no data variable). Since #19 coveralls should not fail on files with bad encoding declarations, so e5ae467 does not help it.

**Comment by sankarravi** [comment]
Here is a version of the file with just the section that we had to fix to make the build start working again:
https://www.dropbox.com/s/qb7f8mh8cggql4r/offending_comment.py?dl=0

When I look at it in SublimeText or TextWrangler, the offending character is rendered as a `$`: it's the second one, in between the two `regsvr32

**Comment by sankarravi** [comment]
Ah yeah, makes sense. Here is a version of the file with just the section that we had to fix to make the build start working again:
https://www.dropbox.com/s/qb7f8mh8cggql4r/offending_comment.py?dl=0

When I look at it in SublimeText or TextWrangler, the offending character is rendered as a `$`: it's the second one, in between the two `regsvr32` commands. However, if I open it in QuickLook on my Mac, it is rendered as a line separator, which is what it originally was on the Windows box it came over from. Hopefully you can repro the bug with it.
