### ISSUE TITLE
Dealing with Multiple Coverage Results 

### ISSUE THREAD

**Issue by cancan101** [coveralls-clients/coveralls-python#72]
My repos is laid out as:

```
/
/.travis.yml
/projects/
         /p1
         /p2
         /p3
```

and I am running: `coverage run --source="." ./manage.py test` from within each each of the projects folders (i.e. a `.coverage` file is created within `p1`, `p2` and `p3`).

How do I take these coverage files, merge them and submit to coveralls also making sure the paths are correct?

**Comment by jessamynsmith** [comment]
Is there a reason you don't run coverage from the top level, on all projects at once? The merge functionality is available, but more for merging in other formats. Here is an example of me merging in JavaScript coverage: https://github.com/jessamynsmith/eggtimer-server/blob/master/circle.yml

**Comment by cancan101** [comment]
The projects are totally separate code bases with different requirements, test runners etc (I have shown them all above using the Django runner, but some may be using `nose` / `unittest`).

**Comment by coagulant** [comment]
Have you tried `coverage combine`? Not sure about matching paths though.

**Comment by lakshmi-kannan** [comment]
We have a similar problem. Our project has multiple components and we have unit tests/integration tests for them. See https://github.com/StackStorm/st2/blob/master/Makefile#L257. 

Coveralls shows coverage report for only one component (last one in alpha order). See https://coveralls.io/builds/3027736. I'd like the ability to merge xml reports and send it to coveralls as a CLI option. Some code for this is already available here - https://github.com/x3mSpeedy/Flow123d-python-utils/blob/master/src/coverage/coverage_merge_module.py. 
I could use that to merge on my side (`coverage combine` didn't work) but it would be beneficial if coveralls did this merge.

**Comment by cancan101** [comment]
Right now I am using https://github.com/z4r/python-coveralls and just calling:
```
coveralls --data_file=path/to/.coverage;
```
in `after_success` for each run.

**Comment by TheKevJames** [comment]
I recently updated the documentation on merging multiple coverage results. You can find it [here](http://coveralls-python.readthedocs.io/en/latest/usage/multilang.html).

**Comment by tysonclugg** [comment]
@TheKevJames The updated docs suggest using `coveralls-lcov` which isn't part of this package, nor is it even part of the Python ecosystem.  I don't feel that's an adequate response for this project, especially for projects that have no Ruby software components.
