### ISSUE TITLE
Reporting coverage on test files?

### ISSUE THREAD

**Issue by lukeyeager** [coveralls-clients/coveralls-python#85]
**Coveralls includes test files in the coverage, even though nosetests doesn't seem to be generating coverage for them.**

Coveralls job: https://coveralls.io/builds/3297384
TravisCI build: https://travis-ci.org/NVIDIA/DIGITS/builds/75482271
Here is how I invoke `nosetests` and `coveralls`: https://github.com/NVIDIA/DIGITS/blob/df401d9c52/.travis.yml#L33-L35

I'm not running `nosetests` with the `--cover-tests` option, and I can verify by looking at the TravisCI log. Coverage is not reported for the `test_*.py` files in the log, and the overall coverage is reported as 72%.

However, the overall coverage reported by Coveralls is 74.9%, because coverage for the `test_*.py` files is included. What gives? How was that coverage information even generated if not by `nose`?

FYI [I'm requiring](https://github.com/NVIDIA/DIGITS/blob/df401d9c52ceadd85b117ac25148795723466213/requirements_test.txt#L7) `coveralls>=0.5`, and TravisCI is installing version 0.5.

**Comment by aiboy** [comment]
just change your script line in .travis-ci to this

coverage run --omit=*/tests/* --source=[YOURPACKAGENAME] setup.py test 

and in your setup.py add this

        test_suite='nose.collector',
	tests_require=['nose']

Now tests if not reported
